baseURL = "https://eikekarbe.com/"
languageCode = "en-us"
title = 'Eike Christian Karbe'
theme = []

[params]
  description = "I build specialized web applications focusing on performance, endurance sports, and data analysis."
  github = "https://github.com/ekarbe"
  email = "eike@eikekarbe.com"
  strava = "https://www.strava.com/athletes/58442765"
